{
 "title": "DELL Monitoring",
 "tags": [
  "snmp",
  "dell"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "label_values(chassisModelName,kubernetes_name)"
   },
   {
    "name": "power",
    "query": "label_values(powerSupplyStatus{kubernetes_name=~\"$server\"},powerSupplyIndex)"
   },
   {
    "name": "sensor",
    "query": "systemStateAmperageStatusCombined,systemStateBatteryStatusCombined,systemStateChassisIntrusionStatusCombined,systemStateCoolingDeviceStatusCombined,systemStateCoolingUnitStatusCombined,systemStateMemoryDeviceStatusCombined,systemStatePowerSupplyStatusCombined,systemStatePowerUnitStatusCombined,systemStateProcessorDeviceStatusCombined,systemStateSDCardDeviceStatusCombined,systemStateTemperatureStatusCombined,systemStateVoltageStatusCombined"
   },
   {
    "name": "raid",
    "query": "agentGlobalSystemStatus,batteryStatus"
   },
   {
    "name": "disk",
    "query": "label_values(virtualDiskLayout,virtualDiskNumber)"
   },
   {
    "name": "hwmon",
    "query": "label_values(node_hwmon_temp_celsius{instance=~\"$server.*\"},sensor)"
   }
  ]
 },
 "panels": [
  { "title": "Server Infos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Model Name",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "chassisModelName{kubernetes_name=~\"$server\"}",
     "legendFormat": "{{chassisModelName}}"
    }
   ]
  },
  {
   "title": "TagName",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "chassisServiceTagName{kubernetes_name=~\"$server\"}",
     "legendFormat": "{{chassisServiceTagName}}"
    }
   ]
  },
  {
   "title": "RAID",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "controllerName{kubernetes_name=~\"$server\"}",
     "legendFormat": "{{controllerName}}"
    }
   ]
  },
  {
   "title": "Global Status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "globalStatus{kubernetes_name=~\"$server\"}"
    }
   ]
  },
  {
   "title": "PowerSupply $power",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "repeat": "power",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "powerSupplyStatus{kubernetes_name=~\"$server\",powerSupplyIndex=~\"$power\"}"
    }
   ]
  },
  {
   "title": "FW RAID",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "controllerFWVersion{kubernetes_name=~\"$server\"}",
     "legendFormat": "{{controllerFWVersion}}"
    }
   ]
  },
  {
   "title": "BIOS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "systemBIOSVersionName{kubernetes_name=~\"$server\"}",
     "legendFormat": "{{systemBIOSVersionName}}"
    }
   ]
  },
  { "title": "disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "RAID disk $disk",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
   "repeat": "disk",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "virtualDiskLayout{kubernetes_name=~\"$server\",virtualDiskNumber=~\"$disk\"}"
    }
   ]
  },
  {
   "title": "Virtual Disk State $disk",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 8 },
   "repeat": "disk",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "virtualDiskState{kubernetes_name=~\"$server\",virtualDiskNumber=~\"$disk\"}"
    }
   ]
  },
  { "title": "RAID", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "$raid",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 11 },
   "repeat": "raid",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "$raid{kubernetes_name=~\"$server\"}"
    }
   ]
  },
  { "title": "Hardware infos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "$sensor",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 14 },
   "repeat": "sensor",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "$sensor{kubernetes_name=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Power consumption $server",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sum(powerUsageInstantaneousHeadroom{kubernetes_name=~\"$server\"})",
     "legendFormat": "Watts"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temp $server - $sensor",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_hwmon_temp_celsius{instance=~\"$server.*\"}"
      }
     ]
    }
   ]
  },
  { "title": "Events Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Logs $server",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "eventLogRecord{kubernetes_name=~\"$server\"}",
     "legendFormat": "{{eventLogRecord}}"
    }
   ]
  }
 ]
}